//@version=5
indicator(title="AC-1", overlay=true)
a=#ffffff, b=#7777ff, c=#cccccc, d=#ff0000, e=#00ff00, f=#ffff00, z=color.new(a,100)
_c=close

i1=input(title='Exponential Moving Average (EMA)',defval=true)
plot(ta.ema(_c,21),color=i1?d:z), plot(ta.ema(_c,50),color=i1?f:z), plot(ta.ema(_c,200),color=i1?a:z)

i2=input(title='Bollinger Band (BB)',defval=true)
mid=ta.sma(_c,20), stdDev=2*ta.stdev(_c,20)
plot(mid+stdDev,color=i2?b:z), plot(mid-stdDev,color=i2?b:z)

i3=input(title='Parabolic SAR',defval=true)
plot(ta.sar(0.02,0.02,0.2),style=plot.style_cross,color=i3?c:z)

i4=input(title='Pivot',defval=true)
drawLabel(_p,_s) =>
    if not na(_p) and i4
        label.new(bar_index[10],_p,str.tostring(_p,format.mintick),style=_s,color=color.new(a,80),textcolor=c)
drawLabel(ta.pivothigh(10,10),label.style_label_down), drawLabel(ta.pivotlow(10,10),label.style_label_up)

i5=input(title='DeMark',defval=true)
uc=0, dc=0
for i=0 to 9-1 by 1
    uc+=(nz(close[i])>nz(close[i+4])?1:0), dc+=(nz(close[i])<nz(close[i+4])?1:0), dc
drp=dc==9?1:uc==9?-1:0
plotshape(ta.crossover(drp,0),'',shape.labelup,location.belowbar,i5?e:z)
plotshape(ta.crossunder(drp,0),'',shape.labeldown,location.abovebar,i5?d:z)

i6=input(title='Ichimoku Cloud',defval=true)
dc(_l)=>math.avg(ta.lowest(_l),ta.highest(_l))
l1=math.avg(dc(9), dc(26)), l2=dc(52)
plot(dc(9),color=i6?#2962FF:z), plot(dc(26),color=i6?#b71c1c:z), plot(close,offset=-25,color=i6?#43a047:z)
fill(plot(l1,offset=25,color=i6?#a5d6a7:z),plot(l2,offset=25,color=i6?#ef9a9a:z),color=i6?l1>l2?color.new(#43a047,90):color.new(#f44336,90):z)

//i99=input(title='Volume',defval=false)
//plot(volume/_c,style=plot.style_columns,color=open>_c?#b03838:#008060)
