//@version=5
indicator(title="AC-1", overlay=true)
a=#ffffff, c=#cccccc, d=#ff0000, e=#00ff00, f=#ffff00
_c=close

i1=input(title='Exponential Moving Average (EMA)',defval=true)
ema(_l) => _a=2/(_l+1), _s=0.0, _s:=_a*close+(1-_a)*nz(_s[1])
plot(i1?ema(20):na,color=d), plot(i1?ema(50):na,color=f), plot(i1?ema(200):na,color=a)

i1a=input(title='EMA Extra',defval=false)
plot(i1a?ema(8):na,color=#990000), plot(i1a?ema(100):na,color=#ffff88)

i2=input(title='Bollinger Band (BB)',defval=true)
sma() =>
    _s=0.0
    for i=0 to 19
        _s+=close[i]/20
stdDev=2*ta.stdev(_c,20)
plot(i2?sma()+stdDev:na), plot(i2?sma()-stdDev:na)

i3=input(title='Parabolic SAR',defval=true)
plot(i3?ta.sar(0.02,0.02,0.2):na,style=plot.style_cross,color=c)

i4=input(title='Pivot',defval=true)
drawLabel(_p,_s) =>
    if not na(_p) and i4
        label.new(bar_index[10],_p,str.tostring(_p,format.mintick),style=_s,color=color.new(a,80),textcolor=c)
drawLabel(ta.pivothigh(10,10),label.style_label_down), drawLabel(ta.pivotlow(10,10),label.style_label_up)

i5=input(title='DeMark',defval=true)
uc=0, dc=0
for i=0 to 9-1 by 1
    uc+=(nz(close[i])>nz(close[i+4])?1:0), dc+=(nz(close[i])<nz(close[i+4])?1:0), dc
drp=dc==9?1:uc==9?-1:0
plotshape(i5?ta.crossover(drp,0):na,'',shape.labelup,location.belowbar,e)
plotshape(i5?ta.crossunder(drp,0):na,'',shape.labeldown,location.abovebar,d)

i6=input(title='Ichimoku Cloud',defval=false)
dc(_l)=>math.avg(ta.lowest(_l),ta.highest(_l))
l1=math.avg(dc(9), dc(26)), l2=dc(52)
plot(i6?dc(9):na,color=#2962FF), plot(i6?dc(26):na,color=#b71c1c), plot(i6?_c:na,offset=-25,color=#43a047)
fill(plot(i6?l1:na,offset=25,color=#a5d6a7),plot(i6?l2:na,offset=25,color=#ef9a9a),color=l1>l2?color.new(#43a047,90):color.new(#f44336,90))

i7=input(title='Volume',defval=false)
plotshape(i7?volume:na,style=shape.square,location=location.bottom,color=open>_c?#b03838:#008060)
