//@version=5
indicator("AC-2")
a=#ff0000
_h=plot.style_histogram

ema(_p,_l)=>_a=2/(_l+1), _s=0.0, _s:=_a*_p+(1-_a)*nz(_s[1])
sma(_p,_l)=>
    _s=0.0
    for i=0 to _l-1
        _s+=_p[i]/_l

i1=input(title='Impulse MACD',defval=true)
calc_smma(_s,_l)=>_a=0.0, _a:=na(_a[1])?sma(_s,_l):(_a[1]*(_l-1)+_s)/_l
hi=calc_smma(high,34), lo=calc_smma(low,34), mi=ema(hlc3,34)+ema(hlc3,34)-ema(ema(hlc3,34),34)
md=(mi>hi)?(mi-hi):(mi<lo)?(mi-lo):0, sb=sma(md,9)
plot(i1?md:na,color=hlc3>mi?hlc3>hi?#32cd32:#00ff00:hlc3<lo?a:#ffa500,style=_h,linewidth=2)
plot(i1?md-sb:na,color=#7777ff,style=_h,linewidth=2), plot(i1?sb:na,color=#800000,linewidth=2)

i2=input(title='Moving Average Convergence/Divergence (MACD)',defval=true)
macd=ema(close,12)-ema(close,16), signal=ema(macd,9), h=(macd-signal)*10
plot(i2?h:na,style=plot.style_columns,color=h>=0?h[1]<h?color.new(#269b9a,60):color.new(#b2dfdb,60):h[1]<h?color.new(#ffcdd2,60):color.new(#ff5252,60))
