//@version=5
indicator("AC-2")
a=#ff0000
_h=plot.style_histogram

i1=input(title='Impulse MACD',defval=true)
calc_smma(_s,len)=>smma=0.0, smma:=na(smma[1])?ta.sma(_s,len):(smma[1]*(len-1)+_s)/len
hi=calc_smma(high,34), lo=calc_smma(low,34), mi=ta.ema(hlc3,34)+ta.ema(hlc3,34)-ta.ema(ta.ema(hlc3,34),34)
md=(mi>hi)?(mi-hi):(mi<lo)?(mi-lo):0, sb=ta.sma(md,9)
plot(i1?md:na,color=hlc3>mi?hlc3>hi?#32cd32:#00ff00:hlc3<lo?a:#ffa500,style=_h,linewidth=2)
plot(i1?md-sb:na,color=#7777ff,style=_h,linewidth=2), plot(i1?sb:na,color=#800000,linewidth=2)

i2=input(title='Moving Average Convergence/Divergence (MACD)',defval=true)
macd=ta.ema(close,12)-ta.ema(close,16), signal=ta.ema(macd,9), h=(macd-signal)*10
plot(i2?h:na,style=plot.style_columns,color=h>=0?h[1]<h?color.new(#269b9a,60):color.new(#b2dfdb,60):h[1]<h?color.new(#ffcdd2,60):color.new(#ff5252,60))
